apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  type: ClusterIP  # Dịch vụ mặc định, chỉ có thể truy cập trong cụm Kubernetes
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-feed
