apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  type: ClusterIP  # Dịch vụ mặc định, chỉ có thể truy cập trong cụm Kubernetes
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    service: frontend
